export const MSG = {
	APP_NAME: "Vibe",
};

export const AUTH_STATUS = {
	EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
	EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
};

export const ADMIN_ACCESS = ["ADMIN", "MODERATOR"];
