/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as homeTermsRouteImport } from './routes/(home)/terms'
import { Route as homeStatusRouteImport } from './routes/(home)/status'
import { Route as homePrivacyRouteImport } from './routes/(home)/privacy'
import { Route as homePricingRouteImport } from './routes/(home)/pricing'
import { Route as homePressRouteImport } from './routes/(home)/press'
import { Route as homeLicensesRouteImport } from './routes/(home)/licenses'
import { Route as homeHelpCenterRouteImport } from './routes/(home)/help-center'
import { Route as homeFeaturesRouteImport } from './routes/(home)/features'
import { Route as homeDownloadRouteImport } from './routes/(home)/download'
import { Route as homeDiscoveryRouteImport } from './routes/(home)/discovery'
import { Route as homeCookiesRouteImport } from './routes/(home)/cookies'
import { Route as homeContactRouteImport } from './routes/(home)/contact'
import { Route as homeCommunityRouteImport } from './routes/(home)/community'
import { Route as homeCareersRouteImport } from './routes/(home)/careers'
import { Route as homeAppsRouteImport } from './routes/(home)/apps'
import { Route as homeAboutRouteImport } from './routes/(home)/about'
import { Route as authVerifyRouteImport } from './routes/(auth)/verify'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as homeMusicRouteRouteImport } from './routes/(home)/music/route'
import { Route as homeMusicIndexRouteImport } from './routes/(home)/music/index'
import { Route as homeMoviesIndexRouteImport } from './routes/(home)/movies/index'
import { Route as homeLibraryIndexRouteImport } from './routes/(home)/library/index'
import { Route as blogBlogIndexRouteImport } from './routes/(blog)/blog/index'
import { Route as adminSettingIndexRouteImport } from './routes/(admin)/setting/index'
import { Route as homePlayPlayIdRouteImport } from './routes/(home)/play/$playId'
import { Route as homeMusicSearchRouteImport } from './routes/(home)/music/search'
import { Route as homeMusicLibraryRouteImport } from './routes/(home)/music/library'
import { Route as homeMusicMusicidRouteImport } from './routes/(home)/music/$musicid'
import { Route as homeMoviesMovieIdRouteImport } from './routes/(home)/movies/$movieId'
import { Route as homeLibraryProfileRouteImport } from './routes/(home)/library/profile'
import { Route as homeExploreSectionRouteImport } from './routes/(home)/explore/$section'
import { Route as blogBlogProfileRouteImport } from './routes/(blog)/blog/profile'
import { Route as blogBlogBlogslugRouteImport } from './routes/(blog)/blog/$blogslug'

const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeTermsRoute = homeTermsRouteImport.update({
  id: '/(home)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const homeStatusRoute = homeStatusRouteImport.update({
  id: '/(home)/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const homePrivacyRoute = homePrivacyRouteImport.update({
  id: '/(home)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const homePricingRoute = homePricingRouteImport.update({
  id: '/(home)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const homePressRoute = homePressRouteImport.update({
  id: '/(home)/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const homeLicensesRoute = homeLicensesRouteImport.update({
  id: '/(home)/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const homeHelpCenterRoute = homeHelpCenterRouteImport.update({
  id: '/(home)/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const homeFeaturesRoute = homeFeaturesRouteImport.update({
  id: '/(home)/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const homeDownloadRoute = homeDownloadRouteImport.update({
  id: '/(home)/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const homeDiscoveryRoute = homeDiscoveryRouteImport.update({
  id: '/(home)/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const homeCookiesRoute = homeCookiesRouteImport.update({
  id: '/(home)/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const homeContactRoute = homeContactRouteImport.update({
  id: '/(home)/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const homeCommunityRoute = homeCommunityRouteImport.update({
  id: '/(home)/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const homeCareersRoute = homeCareersRouteImport.update({
  id: '/(home)/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const homeAppsRoute = homeAppsRouteImport.update({
  id: '/(home)/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const homeAboutRoute = homeAboutRouteImport.update({
  id: '/(home)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyRoute = authVerifyRouteImport.update({
  id: '/(auth)/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const homeMusicRouteRoute = homeMusicRouteRouteImport.update({
  id: '/(home)/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const homeMusicIndexRoute = homeMusicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeMusicRouteRoute,
} as any)
const homeMoviesIndexRoute = homeMoviesIndexRouteImport.update({
  id: '/(home)/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeLibraryIndexRoute = homeLibraryIndexRouteImport.update({
  id: '/(home)/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlogIndexRoute = blogBlogIndexRouteImport.update({
  id: '/(blog)/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const adminSettingIndexRoute = adminSettingIndexRouteImport.update({
  id: '/(admin)/setting/',
  path: '/setting/',
  getParentRoute: () => rootRouteImport,
} as any)
const homePlayPlayIdRoute = homePlayPlayIdRouteImport.update({
  id: '/(home)/play/$playId',
  path: '/play/$playId',
  getParentRoute: () => rootRouteImport,
} as any)
const homeMusicSearchRoute = homeMusicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => homeMusicRouteRoute,
} as any)
const homeMusicLibraryRoute = homeMusicLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => homeMusicRouteRoute,
} as any)
const homeMusicMusicidRoute = homeMusicMusicidRouteImport.update({
  id: '/$musicid',
  path: '/$musicid',
  getParentRoute: () => homeMusicRouteRoute,
} as any)
const homeMoviesMovieIdRoute = homeMoviesMovieIdRouteImport.update({
  id: '/(home)/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const homeLibraryProfileRoute = homeLibraryProfileRouteImport.update({
  id: '/(home)/library/profile',
  path: '/library/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const homeExploreSectionRoute = homeExploreSectionRouteImport.update({
  id: '/(home)/explore/$section',
  path: '/explore/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlogProfileRoute = blogBlogProfileRouteImport.update({
  id: '/(blog)/blog/profile',
  path: '/blog/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlogBlogslugRoute = blogBlogBlogslugRouteImport.update({
  id: '/(blog)/blog/$blogslug',
  path: '/blog/$blogslug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/music': typeof homeMusicRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/verify': typeof authVerifyRoute
  '/about': typeof homeAboutRoute
  '/apps': typeof homeAppsRoute
  '/careers': typeof homeCareersRoute
  '/community': typeof homeCommunityRoute
  '/contact': typeof homeContactRoute
  '/cookies': typeof homeCookiesRoute
  '/discovery': typeof homeDiscoveryRoute
  '/download': typeof homeDownloadRoute
  '/features': typeof homeFeaturesRoute
  '/help-center': typeof homeHelpCenterRoute
  '/licenses': typeof homeLicensesRoute
  '/press': typeof homePressRoute
  '/pricing': typeof homePricingRoute
  '/privacy': typeof homePrivacyRoute
  '/status': typeof homeStatusRoute
  '/terms': typeof homeTermsRoute
  '/': typeof homeIndexRoute
  '/blog/$blogslug': typeof blogBlogBlogslugRoute
  '/blog/profile': typeof blogBlogProfileRoute
  '/explore/$section': typeof homeExploreSectionRoute
  '/library/profile': typeof homeLibraryProfileRoute
  '/movies/$movieId': typeof homeMoviesMovieIdRoute
  '/music/$musicid': typeof homeMusicMusicidRoute
  '/music/library': typeof homeMusicLibraryRoute
  '/music/search': typeof homeMusicSearchRoute
  '/play/$playId': typeof homePlayPlayIdRoute
  '/setting': typeof adminSettingIndexRoute
  '/blog': typeof blogBlogIndexRoute
  '/library': typeof homeLibraryIndexRoute
  '/movies': typeof homeMoviesIndexRoute
  '/music/': typeof homeMusicIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/verify': typeof authVerifyRoute
  '/about': typeof homeAboutRoute
  '/apps': typeof homeAppsRoute
  '/careers': typeof homeCareersRoute
  '/community': typeof homeCommunityRoute
  '/contact': typeof homeContactRoute
  '/cookies': typeof homeCookiesRoute
  '/discovery': typeof homeDiscoveryRoute
  '/download': typeof homeDownloadRoute
  '/features': typeof homeFeaturesRoute
  '/help-center': typeof homeHelpCenterRoute
  '/licenses': typeof homeLicensesRoute
  '/press': typeof homePressRoute
  '/pricing': typeof homePricingRoute
  '/privacy': typeof homePrivacyRoute
  '/status': typeof homeStatusRoute
  '/terms': typeof homeTermsRoute
  '/': typeof homeIndexRoute
  '/blog/$blogslug': typeof blogBlogBlogslugRoute
  '/blog/profile': typeof blogBlogProfileRoute
  '/explore/$section': typeof homeExploreSectionRoute
  '/library/profile': typeof homeLibraryProfileRoute
  '/movies/$movieId': typeof homeMoviesMovieIdRoute
  '/music/$musicid': typeof homeMusicMusicidRoute
  '/music/library': typeof homeMusicLibraryRoute
  '/music/search': typeof homeMusicSearchRoute
  '/play/$playId': typeof homePlayPlayIdRoute
  '/setting': typeof adminSettingIndexRoute
  '/blog': typeof blogBlogIndexRoute
  '/library': typeof homeLibraryIndexRoute
  '/movies': typeof homeMoviesIndexRoute
  '/music': typeof homeMusicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/music': typeof homeMusicRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/verify': typeof authVerifyRoute
  '/(home)/about': typeof homeAboutRoute
  '/(home)/apps': typeof homeAppsRoute
  '/(home)/careers': typeof homeCareersRoute
  '/(home)/community': typeof homeCommunityRoute
  '/(home)/contact': typeof homeContactRoute
  '/(home)/cookies': typeof homeCookiesRoute
  '/(home)/discovery': typeof homeDiscoveryRoute
  '/(home)/download': typeof homeDownloadRoute
  '/(home)/features': typeof homeFeaturesRoute
  '/(home)/help-center': typeof homeHelpCenterRoute
  '/(home)/licenses': typeof homeLicensesRoute
  '/(home)/press': typeof homePressRoute
  '/(home)/pricing': typeof homePricingRoute
  '/(home)/privacy': typeof homePrivacyRoute
  '/(home)/status': typeof homeStatusRoute
  '/(home)/terms': typeof homeTermsRoute
  '/(home)/': typeof homeIndexRoute
  '/(blog)/blog/$blogslug': typeof blogBlogBlogslugRoute
  '/(blog)/blog/profile': typeof blogBlogProfileRoute
  '/(home)/explore/$section': typeof homeExploreSectionRoute
  '/(home)/library/profile': typeof homeLibraryProfileRoute
  '/(home)/movies/$movieId': typeof homeMoviesMovieIdRoute
  '/(home)/music/$musicid': typeof homeMusicMusicidRoute
  '/(home)/music/library': typeof homeMusicLibraryRoute
  '/(home)/music/search': typeof homeMusicSearchRoute
  '/(home)/play/$playId': typeof homePlayPlayIdRoute
  '/(admin)/setting/': typeof adminSettingIndexRoute
  '/(blog)/blog/': typeof blogBlogIndexRoute
  '/(home)/library/': typeof homeLibraryIndexRoute
  '/(home)/movies/': typeof homeMoviesIndexRoute
  '/(home)/music/': typeof homeMusicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/music'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify'
    | '/about'
    | '/apps'
    | '/careers'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/discovery'
    | '/download'
    | '/features'
    | '/help-center'
    | '/licenses'
    | '/press'
    | '/pricing'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/'
    | '/blog/$blogslug'
    | '/blog/profile'
    | '/explore/$section'
    | '/library/profile'
    | '/movies/$movieId'
    | '/music/$musicid'
    | '/music/library'
    | '/music/search'
    | '/play/$playId'
    | '/setting'
    | '/blog'
    | '/library'
    | '/movies'
    | '/music/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify'
    | '/about'
    | '/apps'
    | '/careers'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/discovery'
    | '/download'
    | '/features'
    | '/help-center'
    | '/licenses'
    | '/press'
    | '/pricing'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/'
    | '/blog/$blogslug'
    | '/blog/profile'
    | '/explore/$section'
    | '/library/profile'
    | '/movies/$movieId'
    | '/music/$musicid'
    | '/music/library'
    | '/music/search'
    | '/play/$playId'
    | '/setting'
    | '/blog'
    | '/library'
    | '/movies'
    | '/music'
  id:
    | '__root__'
    | '/(home)/music'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/verify'
    | '/(home)/about'
    | '/(home)/apps'
    | '/(home)/careers'
    | '/(home)/community'
    | '/(home)/contact'
    | '/(home)/cookies'
    | '/(home)/discovery'
    | '/(home)/download'
    | '/(home)/features'
    | '/(home)/help-center'
    | '/(home)/licenses'
    | '/(home)/press'
    | '/(home)/pricing'
    | '/(home)/privacy'
    | '/(home)/status'
    | '/(home)/terms'
    | '/(home)/'
    | '/(blog)/blog/$blogslug'
    | '/(blog)/blog/profile'
    | '/(home)/explore/$section'
    | '/(home)/library/profile'
    | '/(home)/movies/$movieId'
    | '/(home)/music/$musicid'
    | '/(home)/music/library'
    | '/(home)/music/search'
    | '/(home)/play/$playId'
    | '/(admin)/setting/'
    | '/(blog)/blog/'
    | '/(home)/library/'
    | '/(home)/movies/'
    | '/(home)/music/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeMusicRouteRoute: typeof homeMusicRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authVerifyRoute: typeof authVerifyRoute
  homeAboutRoute: typeof homeAboutRoute
  homeAppsRoute: typeof homeAppsRoute
  homeCareersRoute: typeof homeCareersRoute
  homeCommunityRoute: typeof homeCommunityRoute
  homeContactRoute: typeof homeContactRoute
  homeCookiesRoute: typeof homeCookiesRoute
  homeDiscoveryRoute: typeof homeDiscoveryRoute
  homeDownloadRoute: typeof homeDownloadRoute
  homeFeaturesRoute: typeof homeFeaturesRoute
  homeHelpCenterRoute: typeof homeHelpCenterRoute
  homeLicensesRoute: typeof homeLicensesRoute
  homePressRoute: typeof homePressRoute
  homePricingRoute: typeof homePricingRoute
  homePrivacyRoute: typeof homePrivacyRoute
  homeStatusRoute: typeof homeStatusRoute
  homeTermsRoute: typeof homeTermsRoute
  homeIndexRoute: typeof homeIndexRoute
  blogBlogBlogslugRoute: typeof blogBlogBlogslugRoute
  blogBlogProfileRoute: typeof blogBlogProfileRoute
  homeExploreSectionRoute: typeof homeExploreSectionRoute
  homeLibraryProfileRoute: typeof homeLibraryProfileRoute
  homeMoviesMovieIdRoute: typeof homeMoviesMovieIdRoute
  homePlayPlayIdRoute: typeof homePlayPlayIdRoute
  adminSettingIndexRoute: typeof adminSettingIndexRoute
  blogBlogIndexRoute: typeof blogBlogIndexRoute
  homeLibraryIndexRoute: typeof homeLibraryIndexRoute
  homeMoviesIndexRoute: typeof homeMoviesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/terms': {
      id: '/(home)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof homeTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/status': {
      id: '/(home)/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof homeStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/privacy': {
      id: '/(home)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof homePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/pricing': {
      id: '/(home)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof homePricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/press': {
      id: '/(home)/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof homePressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/licenses': {
      id: '/(home)/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof homeLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/help-center': {
      id: '/(home)/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof homeHelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/features': {
      id: '/(home)/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof homeFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/download': {
      id: '/(home)/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof homeDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/discovery': {
      id: '/(home)/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof homeDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/cookies': {
      id: '/(home)/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof homeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/contact': {
      id: '/(home)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof homeContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/community': {
      id: '/(home)/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof homeCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/careers': {
      id: '/(home)/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof homeCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/apps': {
      id: '/(home)/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof homeAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/about': {
      id: '/(home)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof homeAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify': {
      id: '/(auth)/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof authVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/music': {
      id: '/(home)/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof homeMusicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/music/': {
      id: '/(home)/music/'
      path: '/'
      fullPath: '/music/'
      preLoaderRoute: typeof homeMusicIndexRouteImport
      parentRoute: typeof homeMusicRouteRoute
    }
    '/(home)/movies/': {
      id: '/(home)/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof homeMoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/library/': {
      id: '/(home)/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof homeLibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog/': {
      id: '/(blog)/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof blogBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/setting/': {
      id: '/(admin)/setting/'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof adminSettingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/play/$playId': {
      id: '/(home)/play/$playId'
      path: '/play/$playId'
      fullPath: '/play/$playId'
      preLoaderRoute: typeof homePlayPlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/music/search': {
      id: '/(home)/music/search'
      path: '/search'
      fullPath: '/music/search'
      preLoaderRoute: typeof homeMusicSearchRouteImport
      parentRoute: typeof homeMusicRouteRoute
    }
    '/(home)/music/library': {
      id: '/(home)/music/library'
      path: '/library'
      fullPath: '/music/library'
      preLoaderRoute: typeof homeMusicLibraryRouteImport
      parentRoute: typeof homeMusicRouteRoute
    }
    '/(home)/music/$musicid': {
      id: '/(home)/music/$musicid'
      path: '/$musicid'
      fullPath: '/music/$musicid'
      preLoaderRoute: typeof homeMusicMusicidRouteImport
      parentRoute: typeof homeMusicRouteRoute
    }
    '/(home)/movies/$movieId': {
      id: '/(home)/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof homeMoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/library/profile': {
      id: '/(home)/library/profile'
      path: '/library/profile'
      fullPath: '/library/profile'
      preLoaderRoute: typeof homeLibraryProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/explore/$section': {
      id: '/(home)/explore/$section'
      path: '/explore/$section'
      fullPath: '/explore/$section'
      preLoaderRoute: typeof homeExploreSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog/profile': {
      id: '/(blog)/blog/profile'
      path: '/blog/profile'
      fullPath: '/blog/profile'
      preLoaderRoute: typeof blogBlogProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog/$blogslug': {
      id: '/(blog)/blog/$blogslug'
      path: '/blog/$blogslug'
      fullPath: '/blog/$blogslug'
      preLoaderRoute: typeof blogBlogBlogslugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface homeMusicRouteRouteChildren {
  homeMusicMusicidRoute: typeof homeMusicMusicidRoute
  homeMusicLibraryRoute: typeof homeMusicLibraryRoute
  homeMusicSearchRoute: typeof homeMusicSearchRoute
  homeMusicIndexRoute: typeof homeMusicIndexRoute
}

const homeMusicRouteRouteChildren: homeMusicRouteRouteChildren = {
  homeMusicMusicidRoute: homeMusicMusicidRoute,
  homeMusicLibraryRoute: homeMusicLibraryRoute,
  homeMusicSearchRoute: homeMusicSearchRoute,
  homeMusicIndexRoute: homeMusicIndexRoute,
}

const homeMusicRouteRouteWithChildren = homeMusicRouteRoute._addFileChildren(
  homeMusicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  homeMusicRouteRoute: homeMusicRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authVerifyRoute: authVerifyRoute,
  homeAboutRoute: homeAboutRoute,
  homeAppsRoute: homeAppsRoute,
  homeCareersRoute: homeCareersRoute,
  homeCommunityRoute: homeCommunityRoute,
  homeContactRoute: homeContactRoute,
  homeCookiesRoute: homeCookiesRoute,
  homeDiscoveryRoute: homeDiscoveryRoute,
  homeDownloadRoute: homeDownloadRoute,
  homeFeaturesRoute: homeFeaturesRoute,
  homeHelpCenterRoute: homeHelpCenterRoute,
  homeLicensesRoute: homeLicensesRoute,
  homePressRoute: homePressRoute,
  homePricingRoute: homePricingRoute,
  homePrivacyRoute: homePrivacyRoute,
  homeStatusRoute: homeStatusRoute,
  homeTermsRoute: homeTermsRoute,
  homeIndexRoute: homeIndexRoute,
  blogBlogBlogslugRoute: blogBlogBlogslugRoute,
  blogBlogProfileRoute: blogBlogProfileRoute,
  homeExploreSectionRoute: homeExploreSectionRoute,
  homeLibraryProfileRoute: homeLibraryProfileRoute,
  homeMoviesMovieIdRoute: homeMoviesMovieIdRoute,
  homePlayPlayIdRoute: homePlayPlayIdRoute,
  adminSettingIndexRoute: adminSettingIndexRoute,
  blogBlogIndexRoute: blogBlogIndexRoute,
  homeLibraryIndexRoute: homeLibraryIndexRoute,
  homeMoviesIndexRoute: homeMoviesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
